### PR TITLE
Update updateNames.php

### PR DESCRIPTION
**Pull request by PunKeel**
Fix grabLatestIgn if it was non working ... not really sure ^^

### CODE REVIEW

**Comment by lol768** [comment]
Good catch, thanks!

**Comment by PunKeel** [comment]
You're welcome :)

**Comment by lol768** [comment]
Do you use IRC? You can PM me on EsperNet (preferred) or freenode. Nick is lol768.

**Comment by lol768** [comment]
@PunKeel Since I missed you on IRC (been away for a bit), just wanted to say you're very welcome :)

**Pull request merged**
