### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by bionicrm**
lol768 would approve.

### CODE REVIEW

**Comment by lol768** [comment]
I found the G in rich diff mode which gives word wrap :grinning:

**Comment by bionicrm** [comment]
darn, i figured you were the only one in the world to use whatever alternative there is i've never heard of

**Comment by lol768** [comment]
https://github.com/lol768/XenForo-MCASSOC/pull/8/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by bionicrm** [comment]
yeah, silly

**Pull request closed without merging**
